### ISSUE TITLE
Change error message for having wrong prefix commands

### ISSUE THREAD

**Issue by sunzihan23** [AY2324S1-CS2103T-W15-4/tp#107]
Current code is unable to recognise invalid prefix command behind a valid prefix command, instead it gives an error of invalid format for the valid prefix command.

"add c/cs2100 t/good" gives error "Course code should contain a two or three letter prefix, a four digit course code, and an optional one letter suffix", when it should recognise that "t/" should not be included

**Comment by gongg21** [comment]
Mentioned in Developer's Guide under Appendix: Planned Enhancements
