### ISSUE TITLE
[PE-D][Tester A] Duplicate Person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-4/tp#199]
![image.png](https://raw.githubusercontent.com/ZD292/ped/main/files/9136890b-3592-474f-831f-2dc054c947da.png)
I can add 2 John Doe if they have the same name

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZD292/ped#3

**Comment by phiphi-tan** [comment]
Rejected. Duplicate person check is by email which is confirmed to be unique (NUSNET ID). Duplicate names still exist
