### ISSUE TITLE
[PE-D][Tester A] Sorting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-4/tp#200]
Not quite sure how the sorting function works according to UG and error message

![image.png](https://raw.githubusercontent.com/ZD292/ped/main/files/aa5154b9-ff5c-4a75-a8e6-a989b37b0d10.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZD292/ped#4

**Comment by phiphi-tan** [comment]
should be documentation bug

**Comment by sunzihan23** [comment]
duplicate of #210, fixed with PR #293
