### ISSUE TITLE
[PE-D][Tester A] Home navigation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-4/tp#203]
home command does not bring me to the original page

![image.png](https://raw.githubusercontent.com/ZD292/ped/main/files/6504b382-2d1d-4049-8c61-9390441e731b.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZD292/ped#6

**Comment by phiphi-tan** [comment]
Screenshot shows user at home page, so bug is invalid.

Potential fix: Larger differentiation from home/course page when data is empty
