### ISSUE TITLE
[PE-D][Tester A] Select

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-4/tp#205]
After selecting course I am not able to reselect another course by using e.g. select 1, select 2

![image.png](https://raw.githubusercontent.com/ZD292/ped/main/files/66625b0c-aca9-437c-b32b-5744a522c7ac.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZD292/ped#8

**Comment by phiphi-tan** [comment]
Was not our intended function but will look into doing that
