### ISSUE TITLE
[PE-D][Tester B] Find command accepts multiple keywords

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W15-4/tp#228]
![image.png](https://raw.githubusercontent.com/jason-raiin/ped/main/files/cc879fd9-4b57-44e4-a5d8-49dbe965bc26.png)

UG implies that only one word is allowed for the `find` command, but the functionality allows for multiple words and gives the combined search result for each word 

![image.png](https://raw.githubusercontent.com/jason-raiin/ped/main/files/15442825-a924-4d34-876d-f14d89b2065d.png)

![image.png](https://raw.githubusercontent.com/jason-raiin/ped/main/files/74909126-b376-4b43-924e-23b363471641.png)

![image.png](https://raw.githubusercontent.com/jason-raiin/ped/main/files/c79259eb-4252-4ddd-9c27-29751b7cb5fd.png)

UG should be updated to reflect this functionality (it's probably a beneficial feature?)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jason-raiin/ped#7

**Comment by devanshubisht** [comment]
The issue was with the UG and not the functionality of the `find`. We have edited the UG to reflect the accurate result of the command.
